### ISSUE TITLE
Updates to the Code

### ISSUE THREAD

**Issue by steve3d2005** [sam-tj/DigitalClockSmartShelvingWithESP#1]
Hi sam-tj,

I have built the LED Clock  and found your code worked great for getting it up and running.

I have been making some modifications in order to integrate it with Blynk.

I have added the ability to 
Change Hour and Minute Colors via Blynk
Change Downlight Brightness via Blynk
Adjust the clock for Daylight Savings Time via Blynk

I still would like to do some additional things but I am pretty new at the whole arduino stuff.

If you have any concerns with using  your code as a foundation for my changes please let me know.

Thanks,
Steve

**Comment by sam-tj** [comment]
Sure Steve, using it with Blynk is a great Idea.

You can also use my other code on clocks which has an alternate approach of getting Time.

Feel free to connect with any new projects and queries.

--
Sameer
